config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: "users", controllers: { sessions: "users/sessions", registrations: "users/registrations", password: "users/passwords"}, path_names: { sign_in: "login", sign_up: "register", sign_out: "logout" }
  devise_for :admins
  root 'pages#index'
  resources 'pages'

  # strip
  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
    get 'success', to: 'checkout#success', as: 'checkout_success'
  end

  # admin
  namespace :admin do
    root 'my_admins#index'
    resources 'products'
    resources 'orders'
  end

  # users
  get 'user', to: 'users#index'
  namespace :user do
    resources 'orders', except: 'new'
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/my-admin.rb
class ApplicationAdminController < ApplicationRecord

end 

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :product, optional: true

  enum status: [:pending, :process, :success]
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :orders
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders
end

app/models/user_dashboard.rb
class UserDashboard < ApplicationRecord

end 

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationAdminController

  def index
    @orders = Order.all
  end

  def new
  end

  def show
  end

  def destroy
  end

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationAdminController

  def index
    @adm_products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    @product.save!
    if @product.save
      redirect_to admin_products_path
    else
      render 'new'
    end
  end

  def destroy
  end

  private

  def product_params
    params.require(:product).permit(:product_name, :description, :rating, :price, :admin_id)
  end

end

app/controllers/admins/unlocks_controller.rb
# frozen_string_literal: true

class Admins::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_admin_controller.rb
class ApplicationAdminController < ActionController::Base
  # before_action :authenticate_admin!
  layout "admin-dashboards"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def new
  end

def create
  # Amount in cents
  @amount = 500

  customer = User.create({
    email: params[:email],
    source: params[:stripeToken],
  })

  charge = Stripe::Charge.create({
    # customer: customer.id,
    amount: @amount,
    description: 'Rails Stripe customer',
    currency: 'usd',
  })

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end

end

app/controllers/checkout_controller.rb
  def create
    product = Product.find(params[:id])

    if product.nil?
      redirect_to root_path
      return
    end

    @session = Stripe::Checkout::Session.create(
      payment_method_types: ['card'],
      line_items: [
        {
          name: product.product_name,
          description: product.description,
          amount: product.total_price,
          currency: 'idr',
          quantity: 1
        }
      ],
      success_url: checkout_success_url,
      cancel_url: checkout_cancel_url
    )
    respond_to do |format|
      format.js
    end

    def success
      @session = Stripe::Checkout::Session.retrieve(params[:session_id])
      @payment_intent = Stripe::PaymentIntent.retrieve(@session.payment_intent)
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @products = Product.all
    @order = Order.new
  end

  def create
    @order = Order.new(order_params)
    if @order.save!
      # redirect_to root_path
    else
      render 'index'
    end
  end

  private

  def order_params
    params.require(:order).permit(:user_id, :product_id, :shipping_costs, :total_price, :status )
  end

end

app/controllers/user/orders_controller.rb
class User::OrdersController < ApplicationController
before_action :authenticate_user!

  def index
    @orders = Order.all
  end

end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/admin/products/index.html.erb
<div class="col-md-9">
    
    <%= link_to 'Add Product', new_admin_product_path, class: "btn btn-success"%>
  
    <br>
    <br>

    <div class="table-responsive">
        <table class="table table-striped table-sm">
            <thead>
                <tr>
                    <th>Product Name</th>
                    <th>Description</th>
                    <th>Price</th>
                </tr>
            </thead>
            <tbody>
            <% @adm_products.each do |s|%>
                <tr>
                    <td><%= s.product_name%></td>
                    <td><%= s.description%></td>
                    <td><%= s.price%></td>
                </tr>
            <% end %>
            </tbody>
        </table>

    </div>

</div>

app/views/admin/products/new.html.erb
<h1>Create New Product</h1>

<%= form_for @product, :url => {:controller => "products"} do |f|%>

  <p>
    <%= f.label :product_name %>
    <%= f.text_field :product_name%>
  </p>
  <p>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.label :price %>
    <%= f.text_field :price %>
  </p>
  <!-- <p> -->
    <%# <%= f.label :rating %>
    <%# <%= f.number_field :rating%>
  <!-- </p> -->
  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: $5.00</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="500"
          data-locale="auto"></script>
<% end %>